/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FulfillmentPolicyRouteImport } from './routes/fulfillment-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ByeRouteImport } from './routes/bye'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as SponsorsLoginRouteImport } from './routes/sponsors.login'
import { Route as SponsorsAccountRouteImport } from './routes/sponsors.account'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ObsVideoRouteImport } from './routes/obs.video'
import { Route as ObsLiveRouteImport } from './routes/obs.live'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiSponsorsPortalRouteImport } from './routes/api/sponsors/portal'
import { Route as ApiSponsorsCheckoutRouteImport } from './routes/api/sponsors/checkout'
import { Route as ApiSponsorsAssetsRouteImport } from './routes/api/sponsors/assets'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSponsorsAssetsAssetIdRouteImport } from './routes/api/sponsors/assets/$assetId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FulfillmentPolicyRoute = FulfillmentPolicyRouteImport.update({
  id: '/fulfillment-policy',
  path: '/fulfillment-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ByeRoute = ByeRouteImport.update({
  id: '/bye',
  path: '/bye',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsLoginRoute = SponsorsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SponsorsRoute,
} as any)
const SponsorsAccountRoute = SponsorsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SponsorsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsVideoRoute = ObsVideoRouteImport.update({
  id: '/obs/video',
  path: '/obs/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsLiveRoute = ObsLiveRouteImport.update({
  id: '/obs/live',
  path: '/obs/live',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSponsorsPortalRoute = ApiSponsorsPortalRouteImport.update({
  id: '/api/sponsors/portal',
  path: '/api/sponsors/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSponsorsCheckoutRoute = ApiSponsorsCheckoutRouteImport.update({
  id: '/api/sponsors/checkout',
  path: '/api/sponsors/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSponsorsAssetsRoute = ApiSponsorsAssetsRouteImport.update({
  id: '/api/sponsors/assets',
  path: '/api/sponsors/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSponsorsAssetsAssetIdRoute =
  ApiSponsorsAssetsAssetIdRouteImport.update({
    id: '/$assetId',
    path: '/$assetId',
    getParentRoute: () => ApiSponsorsAssetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bye': typeof ByeRoute
  '/contact': typeof ContactRoute
  '/fulfillment-policy': typeof FulfillmentPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sponsors': typeof SponsorsRouteWithChildren
  '/terms-of-service': typeof TermsOfServiceRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/obs/live': typeof ObsLiveRoute
  '/obs/video': typeof ObsVideoRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sponsors/account': typeof SponsorsAccountRoute
  '/sponsors/login': typeof SponsorsLoginRoute
  '/courses/': typeof CoursesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sponsors/assets': typeof ApiSponsorsAssetsRouteWithChildren
  '/api/sponsors/checkout': typeof ApiSponsorsCheckoutRoute
  '/api/sponsors/portal': typeof ApiSponsorsPortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/sponsors/assets/$assetId': typeof ApiSponsorsAssetsAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bye': typeof ByeRoute
  '/contact': typeof ContactRoute
  '/fulfillment-policy': typeof FulfillmentPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sponsors': typeof SponsorsRouteWithChildren
  '/terms-of-service': typeof TermsOfServiceRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/obs/live': typeof ObsLiveRoute
  '/obs/video': typeof ObsVideoRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sponsors/account': typeof SponsorsAccountRoute
  '/sponsors/login': typeof SponsorsLoginRoute
  '/courses': typeof CoursesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sponsors/assets': typeof ApiSponsorsAssetsRouteWithChildren
  '/api/sponsors/checkout': typeof ApiSponsorsCheckoutRoute
  '/api/sponsors/portal': typeof ApiSponsorsPortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/sponsors/assets/$assetId': typeof ApiSponsorsAssetsAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bye': typeof ByeRoute
  '/contact': typeof ContactRoute
  '/fulfillment-policy': typeof FulfillmentPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sponsors': typeof SponsorsRouteWithChildren
  '/terms-of-service': typeof TermsOfServiceRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/obs/live': typeof ObsLiveRoute
  '/obs/video': typeof ObsVideoRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sponsors/account': typeof SponsorsAccountRoute
  '/sponsors/login': typeof SponsorsLoginRoute
  '/courses/': typeof CoursesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sponsors/assets': typeof ApiSponsorsAssetsRouteWithChildren
  '/api/sponsors/checkout': typeof ApiSponsorsCheckoutRoute
  '/api/sponsors/portal': typeof ApiSponsorsPortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/sponsors/assets/$assetId': typeof ApiSponsorsAssetsAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bye'
    | '/contact'
    | '/fulfillment-policy'
    | '/privacy-policy'
    | '/sponsors'
    | '/terms-of-service'
    | '/courses/$slug'
    | '/obs/live'
    | '/obs/video'
    | '/products/$slug'
    | '/sponsors/account'
    | '/sponsors/login'
    | '/courses/'
    | '/products/'
    | '/api/auth/$'
    | '/api/sponsors/assets'
    | '/api/sponsors/checkout'
    | '/api/sponsors/portal'
    | '/api/stripe/webhook'
    | '/api/sponsors/assets/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bye'
    | '/contact'
    | '/fulfillment-policy'
    | '/privacy-policy'
    | '/sponsors'
    | '/terms-of-service'
    | '/courses/$slug'
    | '/obs/live'
    | '/obs/video'
    | '/products/$slug'
    | '/sponsors/account'
    | '/sponsors/login'
    | '/courses'
    | '/products'
    | '/api/auth/$'
    | '/api/sponsors/assets'
    | '/api/sponsors/checkout'
    | '/api/sponsors/portal'
    | '/api/stripe/webhook'
    | '/api/sponsors/assets/$assetId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bye'
    | '/contact'
    | '/fulfillment-policy'
    | '/privacy-policy'
    | '/sponsors'
    | '/terms-of-service'
    | '/courses/$slug'
    | '/obs/live'
    | '/obs/video'
    | '/products/$slug'
    | '/sponsors/account'
    | '/sponsors/login'
    | '/courses/'
    | '/products/'
    | '/api/auth/$'
    | '/api/sponsors/assets'
    | '/api/sponsors/checkout'
    | '/api/sponsors/portal'
    | '/api/stripe/webhook'
    | '/api/sponsors/assets/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ByeRoute: typeof ByeRoute
  ContactRoute: typeof ContactRoute
  FulfillmentPolicyRoute: typeof FulfillmentPolicyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SponsorsRoute: typeof SponsorsRouteWithChildren
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  ObsLiveRoute: typeof ObsLiveRoute
  ObsVideoRoute: typeof ObsVideoRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSponsorsAssetsRoute: typeof ApiSponsorsAssetsRouteWithChildren
  ApiSponsorsCheckoutRoute: typeof ApiSponsorsCheckoutRoute
  ApiSponsorsPortalRoute: typeof ApiSponsorsPortalRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fulfillment-policy': {
      id: '/fulfillment-policy'
      path: '/fulfillment-policy'
      fullPath: '/fulfillment-policy'
      preLoaderRoute: typeof FulfillmentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bye': {
      id: '/bye'
      path: '/bye'
      fullPath: '/bye'
      preLoaderRoute: typeof ByeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/login': {
      id: '/sponsors/login'
      path: '/login'
      fullPath: '/sponsors/login'
      preLoaderRoute: typeof SponsorsLoginRouteImport
      parentRoute: typeof SponsorsRoute
    }
    '/sponsors/account': {
      id: '/sponsors/account'
      path: '/account'
      fullPath: '/sponsors/account'
      preLoaderRoute: typeof SponsorsAccountRouteImport
      parentRoute: typeof SponsorsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs/video': {
      id: '/obs/video'
      path: '/obs/video'
      fullPath: '/obs/video'
      preLoaderRoute: typeof ObsVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs/live': {
      id: '/obs/live'
      path: '/obs/live'
      fullPath: '/obs/live'
      preLoaderRoute: typeof ObsLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sponsors/portal': {
      id: '/api/sponsors/portal'
      path: '/api/sponsors/portal'
      fullPath: '/api/sponsors/portal'
      preLoaderRoute: typeof ApiSponsorsPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sponsors/checkout': {
      id: '/api/sponsors/checkout'
      path: '/api/sponsors/checkout'
      fullPath: '/api/sponsors/checkout'
      preLoaderRoute: typeof ApiSponsorsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sponsors/assets': {
      id: '/api/sponsors/assets'
      path: '/api/sponsors/assets'
      fullPath: '/api/sponsors/assets'
      preLoaderRoute: typeof ApiSponsorsAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sponsors/assets/$assetId': {
      id: '/api/sponsors/assets/$assetId'
      path: '/$assetId'
      fullPath: '/api/sponsors/assets/$assetId'
      preLoaderRoute: typeof ApiSponsorsAssetsAssetIdRouteImport
      parentRoute: typeof ApiSponsorsAssetsRoute
    }
  }
}

interface SponsorsRouteChildren {
  SponsorsAccountRoute: typeof SponsorsAccountRoute
  SponsorsLoginRoute: typeof SponsorsLoginRoute
}

const SponsorsRouteChildren: SponsorsRouteChildren = {
  SponsorsAccountRoute: SponsorsAccountRoute,
  SponsorsLoginRoute: SponsorsLoginRoute,
}

const SponsorsRouteWithChildren = SponsorsRoute._addFileChildren(
  SponsorsRouteChildren,
)

interface ApiSponsorsAssetsRouteChildren {
  ApiSponsorsAssetsAssetIdRoute: typeof ApiSponsorsAssetsAssetIdRoute
}

const ApiSponsorsAssetsRouteChildren: ApiSponsorsAssetsRouteChildren = {
  ApiSponsorsAssetsAssetIdRoute: ApiSponsorsAssetsAssetIdRoute,
}

const ApiSponsorsAssetsRouteWithChildren =
  ApiSponsorsAssetsRoute._addFileChildren(ApiSponsorsAssetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ByeRoute: ByeRoute,
  ContactRoute: ContactRoute,
  FulfillmentPolicyRoute: FulfillmentPolicyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SponsorsRoute: SponsorsRouteWithChildren,
  TermsOfServiceRoute: TermsOfServiceRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  ObsLiveRoute: ObsLiveRoute,
  ObsVideoRoute: ObsVideoRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSponsorsAssetsRoute: ApiSponsorsAssetsRouteWithChildren,
  ApiSponsorsCheckoutRoute: ApiSponsorsCheckoutRoute,
  ApiSponsorsPortalRoute: ApiSponsorsPortalRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
