/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FulfillmentPolicyRouteImport } from './routes/fulfillment-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ByeRouteImport } from './routes/bye'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FulfillmentPolicyRoute = FulfillmentPolicyRouteImport.update({
  id: '/fulfillment-policy',
  path: '/fulfillment-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ByeRoute = ByeRouteImport.update({
  id: '/bye',
  path: '/bye',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bye': typeof ByeRoute
  '/contact': typeof ContactRoute
  '/fulfillment-policy': typeof FulfillmentPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bye': typeof ByeRoute
  '/contact': typeof ContactRoute
  '/fulfillment-policy': typeof FulfillmentPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bye': typeof ByeRoute
  '/contact': typeof ContactRoute
  '/fulfillment-policy': typeof FulfillmentPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bye'
    | '/contact'
    | '/fulfillment-policy'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/courses/$slug'
    | '/products/$slug'
    | '/courses/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bye'
    | '/contact'
    | '/fulfillment-policy'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/courses/$slug'
    | '/products/$slug'
    | '/courses'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/bye'
    | '/contact'
    | '/fulfillment-policy'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/courses/$slug'
    | '/products/$slug'
    | '/courses/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ByeRoute: typeof ByeRoute
  ContactRoute: typeof ContactRoute
  FulfillmentPolicyRoute: typeof FulfillmentPolicyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fulfillment-policy': {
      id: '/fulfillment-policy'
      path: '/fulfillment-policy'
      fullPath: '/fulfillment-policy'
      preLoaderRoute: typeof FulfillmentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bye': {
      id: '/bye'
      path: '/bye'
      fullPath: '/bye'
      preLoaderRoute: typeof ByeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ByeRoute: ByeRoute,
  ContactRoute: ContactRoute,
  FulfillmentPolicyRoute: FulfillmentPolicyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
